### ISSUE TITLE
Bug- File upload is not going through proxy 

### ISSUE THREAD

**Issue by susilparida** [k8-proxy/gp-filedrop-website#14]
![Upload_bug](https://user-images.githubusercontent.com/70517404/97959582-aba6b180-1dd5-11eb-82d7-ed02a2e8e617.png)

When file gets uploaded in https://glasswall-file-drop.com.glasswall-icap.com/ should go through proxy. Now files uploaded are processed through the proxy.

**Comment by hongson1981** [comment]
[icap_log.txt](https://github.com/k8-proxy/gp-filedrop-website/files/5481825/icap_log.txt)
I update log file to show that payload encoding base64 always pass through ICAP server ( response 204),
You can use domain glasswall-file-drop.com.glasswall-icap.com to check and test
